spring:
  application:
    name: basic
  r2dbc:
    pool:
      max-size: '20'
      initial-size: '5'
      max-idle-time: 30m
      validation-query: SELECT 1
    password: root
    url: r2dbc:pool:mysql://localhost:3307/test
    username: root


rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      virtualHost: tmn-th-alpha
      username: consumer
      password: consumer
      group: consumer
      content-type: application/json

mail:
  host: localhost
  port: 8025
  timeout: 90000
  connectionTimeout: 90000
  retry-attempts: 3
  retry-interval: 5000