spring:
  application:
    name: basic

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      username: guest
      password: guest
      group: consumer
      exchange: emails
      queue: emails