spring:
  application:
    name: basic

rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      virtualHost: tmn-th-alpha
      username: consumer
      password: consumer
      group: consumer